name: verify mkdocs build
on: [pull_request]
jobs:
  verify-docs:
    name: Verify docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Build site
        run: mkdocs build --strict
